version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  php-fpm:
    build: .
    container_name: php_fpm
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3312:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge